[package]
name = "ceramic"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "ceramic"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.10.0"

[dev-dependencies]
marine-rs-sdk-test = "0.10.0"
